blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://skforecast.org/
    about: Check the documentation before opening a new issue.
  - name: ğŸ’¬ Discussions
    url: https://github.com/skforecast/skforecast/discussions
    about: If none of these options fit, your question or topic may be better suited to a discussion.
  - name: ğŸ–¥ï¸ Skforecast Studio
    url: https://studio.skforecast.org/
    about: "Interactive no-code application for building time series forecasting models with skforecast."
  - name: ğŸ§ Discord Community
    url: https://discord.gg/3V52qpNkuj
    about: "Join our Discord server to chat with the community and maintainers."
