blank_issues_enabled: true
contact_links:
  - name: ðŸ“š Documentation
    url: https://skforecast.org/
    about: "Check the documentation before opening a new issue."
  - name: ðŸ’¬ Discussions
    url: https://github.com/skforecast/skforecast/discussions
    about: "If none of these options fit, your question or topic may be better suited to a discussion."
